spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    password: password
    username: sa

server:
  port : 8080